name: dialog
on:
  push:
    branches:
    paths-ignore: ["README.md"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-dialog
        uses: actions/checkout@v2
        with:
          path: "./dialog"
      - name: docker setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: mozillareality
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: docker build(x) push
        uses: docker/build-push-action@v2
        with:
          context: dialog/
          file: dialog/Dockerfile
          tags: mozillareality/${{ github.workflow }}:${{ github.run_number  }}
          cache-from: type=registry,ref=mozillareality/${{ github.workflow }}:buildcache
          cache-to: type=registry,ref=mozillareality/${{ github.workflow }}:buildcache,mode=max
          push: true
  promote:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/feature/gha-fixes'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "master: pull GITHUB_RUN_NUMBER and tag to ${GITHUB_SHA::7} and dev"
        run: |
          fromTag=mozillareality/${{ github.workflow }}:${{ github.run_number }}
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username mozillareality --password-stdin
          toTag=mozillareality/${{ github.workflow }}:${GITHUB_SHA::7}
          echo "[info] promoting :$fromTag to :$toTag"          
          docker pull $fromTag && docker tag $fromTag $toTag && sudo docker push $toTag
          toTag=mozillareality/${{ github.workflow }}:dev
          echo "[info] promoting :$fromTag to :$toTag"          
          docker pull $fromTag && docker tag $fromTag $toTag && sudo docker push $toTag
  release_staging:
    runs-on: ubuntu-latest
    needs: promote
    environment: staging
    steps:
      - name: "pull ${GITHUB_SHA::7} and tag to staging"
        run: |
          fromTag=mozillareality/${{ github.workflow }}:${GITHUB_SHA::7}
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username mozillareality --password-stdin
          toTag=mozillareality/${{ github.workflow }}:staging                    
          echo "[info] promoting :$fromTag to :$toTag"
          docker pull $fromTag && docker tag $fromTag $toTag && sudo docker push $toTag
      - name: checkout codebase for tagging
        uses: actions/checkout@v2
        with:
          path: ./staging
      - name: tag staging commit
        run: |
          cd ./staging
          tag="staging.$(date '+%y%m%d').GITHUB_RUN_NUMBER"
          git tag $tag ${GITHUB_SHA::7} && git push origin $tag
  release_prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: promote
    steps:
      - name: promote artifact to prod
        run: |
          fromTag=mozillareality/${{ github.workflow }}:${GITHUB_SHA::7}
          toTag=mozillareality/${{ github.workflow }}:prod
          echo "promoting :$fromTag to :$toTag"
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username mozillareality --password-stdin
          docker pull $fromTag && docker tag $fromTag $toTag && sudo docker push $toTag
      - name: checkout codebase for tagging
        uses: actions/checkout@v2
        with:
          path: ./prod
      - name: tag release commit
        run: |
          cd ./prod
          tag="prod.$(date '+%y%m%d').GITHUB_RUN_NUMBER"
          git tag $tag ${GITHUB_SHA::7} && git push origin $tag       


