name: dialog
on:
  push:
    paths-ignore: ["README.md"]
  workflow_dispatch:

env:
  registryName: mozillareality
  containerName: dialog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-dialog
        uses: actions/checkout@v2
        with:
          path: "./dialog"
      - name: docker setup buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ env.registryName }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - name: docker build(x) push
        uses: docker/build-push-action@v2
        with:
          context: dialog/
          file: dialog/Dockerfile
          tags: ${{ env.registryName }}/${{ env.containerName }}:${{ github.run_number  }}
          cache-from: type=registry,ref=${{ env.registryName }}/${{ env.containerName }}:buildcache
          cache-to: type=registry,ref=${{ env.registryName }}/${{ env.containerName }}:buildcache,mode=max
          push: true
  promote:
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ghatesting'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "master: pull GITHUB_RUN_NUMBER and tag to ${GITHUB_SHA::7} and dev"
        run: |
          fromTag=${{ env.registryName }}/${{ env.containerName }}:${{ github.run_number }}
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin
          toTag=${{ env.registryName }}/${{ env.containerName }}:${GITHUB_SHA::7}
          echo "[info] promoting :$fromTag to :$toTag"          
          docker pull $fromTag && docker tag $fromTag $toTag && sudo docker push $toTag
          toTag=${{ env.registryName }}/${{ env.containerName }}:dev
          echo "[info] promoting :$fromTag to :$toTag"          
          docker pull $fromTag && docker tag $fromTag $toTag && sudo docker push $toTag
  release_staging:
    runs-on: ubuntu-latest
    needs: promote
    environment: staging
    steps:
      - name: "pull ${GITHUB_SHA::7} and tag to staging"
        run: |
          fromTag=${{ env.registryName }}/${{ env.containerName }}:${GITHUB_SHA::7}
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin
          toTag=${{ env.registryName }}/${{ env.containerName }}:staging                    
          echo "[info] promoting :$fromTag to :$toTag"
          docker pull $fromTag && docker tag $fromTag $toTag && sudo docker push $toTag
      - name: checkout codebase for tagging
        uses: actions/checkout@v2
        with:
          path: ./staging
      - name: tag staging commit
        run: |
          cd ./staging
          tag="staging.$(date '+%y%m%d')"
          git tag $tag ${GITHUB_SHA::7} && git push origin ${GITHUB_SHA::7}
  release_prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: promote
    steps:
      - name: promote artifact to prod
        run: |
          fromTag=${{ env.registryName }}/${{ env.containerName }}:${GITHUB_SHA::7}
          toTag=${{ env.registryName }}/${{ env.containerName }}:prod
          echo "promoting :$fromTag to :$toTag"
          echo ${{ secrets.DOCKER_HUB_PWD }} | sudo docker login --username $registryName --password-stdin
          docker pull $fromTag && docker tag $fromTag $toTag && sudo docker push $toTag
      - name: checkout codebase for tagging
        uses: actions/checkout@v2
        with:
          path: ./staging
      - name: tag release commit
        run: |
          cd ./staging
          tag="prod.$(date '+%y%m%d')"
          git tag $tag ${GITHUB_SHA::7} && git push origin ${GITHUB_SHA::7}          


