name: dialog
on:
  push:
    branches:
    paths-ignore: ["README.md"]
  workflow_dispatch:

jobs:
  turkeyGitops:
    needs: build
    uses: mozilla/hubs-ops/.github/workflows/turkeyGitops.yml@feature/gha-template

